# 1. Använd officiell Node-bild
FROM node:20

# 2. Ange arbetskatalog
WORKDIR /app

# 3. Kopiera package.json och installera
COPY package*.json ./
RUN npm install

# 4. Kopiera resten av projektet
COPY . .

# 5. Generera Prisma-klient
RUN npx prisma generate

# 6. Ange miljövariabler för production (kan överskridas i ECS)
ENV NODE_ENV=production

# 7. Ange porten som ska exponeras
EXPOSE 3001

# 8. Starta appen
CMD ["npm", "start"]